#!/bin/bash
# Runs INSIDE an AgentTier fix-sandbox. Clones the repo, lets Claude Code fix
# the reported bug, pushes a branch, and opens a PR. Inputs come from env vars
# plus two data files (issue title/body) that the caller writes via base64 so
# untrusted issue text is never interpreted as shell.
#
# Required env: GH_TOKEN, REPO (owner/name), BRANCH, ISSUE_NUMBER
# Required files: /workspace/issue_title.txt, /workspace/issue_body.txt
set -euo pipefail

ISSUE_TITLE="$(cat /workspace/issue_title.txt)"
ISSUE_BODY="$(cat /workspace/issue_body.txt)"

cd /workspace
rm -rf work
git clone -q "https://github.com/${REPO}.git" work
cd work
git checkout -q -b "${BRANCH}"

PROMPT="A bug was reported in this repository. Investigate and fix it with a
minimal change, following CLAUDE.md and any relevant skill in .claude/skills.
Do not refactor unrelated code.

Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}

${ISSUE_BODY}

Edit the source files to fix the bug. When finished, give a 2-3 sentence
summary: the root cause and the exact change you made."

echo ">>> Claude is working on the fix..."
claude -p "${PROMPT}" --permission-mode bypassPermissions > /workspace/claude.out 2>/workspace/claude.err || true
SUMMARY="$(grep -v 'WARN - default STS' /workspace/claude.out | tail -c 1200)"

if git diff --quiet; then
  echo "NO_CHANGES — Claude did not modify any files."
  echo "----- claude stdout -----"; tail -c 1500 /workspace/claude.out
  echo "----- claude stderr -----"; tail -c 800 /workspace/claude.err
  exit 2
fi

echo ">>> Diff produced:"
git --no-pager diff --stat

git config user.email "11687083+hardikvasa@users.noreply.github.com"
git config user.name "AgentTier Bot"
git add -A
git commit -q -m "Fix: ${ISSUE_TITLE} (closes #${ISSUE_NUMBER})"
git push -q "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git" "${BRANCH}"
echo ">>> Pushed branch ${BRANCH}"

PR_BODY="Automated fix for issue #${ISSUE_NUMBER}, generated by Claude Code running in an AgentTier sandbox.

**Claude's summary:**
${SUMMARY}

Closes #${ISSUE_NUMBER}."

# JSON-encode the body safely with python, then open the PR.
PR_PAYLOAD="$(ISSUE_NUMBER="$ISSUE_NUMBER" BRANCH="$BRANCH" ISSUE_TITLE="$ISSUE_TITLE" BODY="$PR_BODY" python3 -c '
import json, os
print(json.dumps({
    "title": "Fix: " + os.environ["ISSUE_TITLE"],
    "head": os.environ["BRANCH"],
    "base": "main",
    "body": os.environ["BODY"],
}))')"

HTTP_OUT="$(curl -s -X POST \
  -H "Authorization: token ${GH_TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/${REPO}/pulls" \
  -d "${PR_PAYLOAD}")"

PR_URL="$(echo "$HTTP_OUT" | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("html_url",""))' 2>/dev/null || true)"
if [ -n "$PR_URL" ]; then
  echo "PR_OPENED ${PR_URL}"
else
  echo "PR_FAILED: $(echo "$HTTP_OUT" | head -c 400)"
  exit 3
fi
